'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/generate-training-module.ts';
import '@/ai/flows/explain-simulation-failure.ts';
import '@/ai/flows/provide-ai-risk-advice.ts';
import '@/ai/flows/surface-ai-insights.ts';
import '@/ai/flows/generate-training-campaigns.ts';
import '@/ai/flows/chat-flow.ts';
import '@/ai/flows/generate-flashcards-flow.ts';
import '@/ai/flows/sms-fraud-flow.ts';
import '@/ai/flows/osint-mind-map-flow.ts';
import '@/ai/flows/email-phishing-flow.ts';
import '@/ai/flows/whatsapp-fraud-flow.ts';
import '@/ai/flows/dark-web-simulation-flow.ts';
import '@/ai/flows/generate-ir-playbook.ts';
import '@/ai/flows/generate-threat-actor-profile.ts';
import '@/ai/flows/generate-escape-room-flow.ts';
import '@/ai/genkit';
