'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Loader, Wand2 } from 'lucide-react';
import {
  generateAndStoreTrainingCampaigns,
  GenerateAndStoreTrainingCampaignsOutput,
} from '@/ai/flows/generate-training-campaigns';
import { useCollection, useFirestore } from '@/firebase';
import { collection } from 'firebase/firestore';
import { TrainingCampaign } from '@/app/training/data';
import { useMemoFirebase } from '@/firebase/provider';
import Link from 'next/link';

export default function AdminPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationResult, setGenerationResult] =
    useState<GenerateAndStoreTrainingCampaignsOutput | null>(null);

  const firestore = useFirestore();
  const campaignsCollection = useMemoFirebase(
    () => (firestore ? collection(firestore, 'trainingCampaigns') : null),
    [firestore]
  );
  const { data: campaigns, isLoading: campaignsLoading } =
    useCollection<TrainingCampaign>(campaignsCollection);

  const handleGenerateCampaigns = async () => {
    setIsGenerating(true);
    setGenerationResult(null);
    try {
      const result = await generateAndStoreTrainingCampaigns({});
      setGenerationResult(result);
    } catch (error) {
      console.error('Failed to generate campaigns:', error);
      setGenerationResult({
        success: false,
        message: 'An error occurred during campaign generation.',
      });
    }
    setIsGenerating(false);
  };

  useEffect(() => {
    // Automatically generate campaigns if they don't exist
    if (!campaignsLoading && campaigns && campaigns.length === 0 && !isGenerating) {
      handleGenerateCampaigns();
    }
  }, [campaigns, campaignsLoading, isGenerating]);


  return (
    <div className="container mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold font-headline">Admin Dashboard</h1>
          <p className="text-muted-foreground">
            Manage your organization&apos;s training and security posture.
          </p>
        </div>
      </div>

      {generationResult && (
        <Card
          className={
            generationResult.success
              ? 'bg-success/10 border-success'
              : 'bg-destructive/10 border-destructive'
          }
        >
          <CardHeader>
            <CardTitle
              className={
                generationResult.success ? 'text-success' : 'text-destructive'
              }
            >
              {generationResult.success
                ? 'Generation Successful'
                : 'Generation Failed'}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p>{generationResult.message}</p>
            {!generationResult.success && (
              <Button onClick={handleGenerateCampaigns} disabled={isGenerating} className="mt-4">
                {isGenerating ? (
                  <Loader className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Wand2 className="mr-2 h-4 w-4" />
                )}
                Retry Generation
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle className="font-headline">
            Available Training Campaigns
          </CardTitle>
          <CardDescription>
            These are the current campaigns stored in Firestore, generated by AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {campaignsLoading || isGenerating ? (
            <div className="flex flex-col justify-center items-center h-48 gap-4">
              <Loader className="h-8 w-8 animate-spin" />
              <p className="text-muted-foreground">
                {isGenerating ? 'Generating initial training campaigns...' : 'Loading campaigns...'}
              </p>
            </div>
          ) : campaigns && campaigns.length > 0 ? (
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {campaigns.map((campaign) => (
                <Card
                  key={campaign.id}
                  className="bg-background hover:bg-accent/50 transition-colors flex flex-col"
                >
                  <CardHeader>
                    <CardTitle className="text-base font-headline">
                      {campaign.title}
                    </CardTitle>
                    <CardDescription className="text-xs h-10">
                      {campaign.description}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="flex-grow flex flex-col justify-end">
                    <Button asChild variant="secondary" size="sm">
                      <Link href={`/training`}>View Campaign</Link>
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          ) : (
             !generationResult?.success && (
              <div className="flex flex-col items-center justify-center text-center h-48 gap-4">
                <p className="text-muted-foreground">
                  No campaigns found. Generation may have failed.
                </p>
             </div>
            )
          )}
        </CardContent>
      </Card>
    </div>
  );
}
