import { type LucideIcon } from 'lucide-react';

export type TrainingModule = {
  id: string;
  title: string;
  description: string;
};

export type TrainingCampaign = {
  id: string;
  title: string;
  description: string;
  duration: string;
  audience: string;
  modules: TrainingModule[];
  activities: string[];
  kpis: string;
  icon: LucideIcon | string; // Allow string for Firestore compatibility
};

// This data is now generated by AI and stored in Firestore.
// This file can be kept for type definitions or removed if types are moved elsewhere.
export const trainingCampaigns: TrainingCampaign[] = [];
