
export const industries = [
    "Technology",
    "Healthcare",
    "Finance",
    "Retail",
    "Education",
    "Manufacturing",
    "Government",
    "Hospitality",
    "Construction",
    "Transportation and Logistics",
    "Energy",
    "Telecommunications",
    "Media and Entertainment",
    "Agriculture",
    "Real Estate",
    "Automotive",
    "Aerospace and Defense",
    "Pharmaceuticals",
    "Biotechnology",
    "Professional Services",
    "Food and Beverage",
    "Consumer Goods",
    "Insurance",
    "Utilities",
    "Mining and Metals",
    "Forestry and Paper",
    "Chemicals",
    "E-commerce",
    "Gaming",
    "Social Media",
    "Software as a Service (SaaS)",
    "Cloud Computing",
    "Artificial Intelligence",
    "Cybersecurity",
    "FinTech",
    "EdTech",
    "HealthTech",
    "Legal Services",
    "Consulting",
    "Marketing and Advertising",
    "Human Resources",
    "Architecture and Design",
    "Non-profit and Charities",
    "Environmental Services",
    "Waste Management",
    "Airlines",
    "Maritime",
    "Railways",
    "Publishing",
    "Broadcasting",
    "Film Production",
    "Music",
    "Fashion and Apparel",
    "Luxury Goods",
    "Sports and Recreation",
    "Fitness and Wellness",
    "Cosmetics",
    "Furniture",
    "Electronics",
    "Home Improvement",
    "Gardening and Landscaping",
    "Veterinary Services",
    "Childcare",
    "Elderly Care",
    "Staffing and Recruiting",
    "Event Management",
    "Security and Investigations",
    "Public Safety",
    "Military",
    "Scientific Research and Development",
    "Venture Capital and Private Equity",
    "Investment Banking",
    "Asset Management",
    "Commercial Banking",
    "Credit Unions",
    "Accounting",
    "Bookkeeping",
    "Insurance Brokerage",
    "Reinsurance",
    "Oil and Gas",
    "Renewable Energy",
    "Nuclear Energy",
    "Electrical Power Generation",
    "Water and Sanitation",
    "Internet Service Providers",
    "Cable and Satellite",
    "Data Centers",
    "Printing",
    "Packaging",
    "Plastics",
    "Textiles",
    "Public Relations",
    "Translation and Localization",
    "Market Research",
    "Graphic Design",
    "Photography",
    "Animation",
    "Fine Arts",
    "Museums and Galleries"
];
