export const roles = [
  "All Employees",
  "Executive Management",
  "Senior Management",
  "Middle Management",
  "Team Leaders",
  "IT Department",
  "IT - Help Desk",
  "IT - System Administrators",
  "IT - Network Engineers",
  "IT - Security Analysts",
  "IT - Database Administrators",
  "Software Developers",
  "DevOps Engineers",
  "QA / Testers",
  "Human Resources",
  "Finance Department",
  "Accounting",
  "Sales Department",
  "Marketing Department",
  "Customer Support",
  "Legal Department",
  "Compliance Officers",
  "Procurement Department",
  "Facilities Management",
  "Administrative Staff",
  "Interns",
  "Contractors",
  "Temporary Staff",
  "Remote Employees",
  "New Hires",
  "Operations Staff",
  "Research and Development",
  "Product Managers",
  "Project Managers",
  "Business Analysts",
  "Data Scientists",
  "Data Analysts",
  "Public Relations",
  "Logistics and Supply Chain",
  "Healthcare - Doctors",
  "Healthcare - Nurses",
  "Healthcare - Administrative",
  "Education - Teachers",
  "Education - Administrators",
  "Retail - Store Associates",
  "Retail - Store Managers",
  "Manufacturing - Plant Workers",
  "Manufacturing - Plant Managers",
  "Government - Public Sector Employees",
  "Financial Services - Tellers",
  "Financial Services - Financial Advisors",
  "Hospitality - Front Desk",
  "Hospitality - Management"
];
