
export const topics = [
  "Phishing Awareness",
  "Password Security",
  "Two-Factor Authentication (2FA)",
  "Social Engineering",
  "Malware and Ransomware",
  "Secure Browsing Habits",
  "Data Privacy and GDPR",
  "Physical Security",
  "Mobile Device Security",
  "Wi-Fi Security",
  "Cloud Security Basics",
  "Incident Response",
  "Secure Software Development Lifecycle (SSDLC)",
  "SQL Injection",
  "Cross-Site Scripting (XSS)",
  "Network Security Fundamentals",
  "Firewalls and Proxies",
  "Encryption and Cryptography",
  "Business Email Compromise (BEC)",
  "Insider Threats",
  "Acceptable Use Policy",
  "Data Classification",
  "Vendor Risk Management",
  "PCI DSS Compliance",
  "HIPAA Security Rule",
  "Identity and Access Management (IAM)",
  "Threat Modeling",
  "Vulnerability Management",
  "Security Information and Event Management (SIEM)",
  "Digital Forensics Basics",
  "IoT Security",
  "API Security",
  "Container Security (Docker, Kubernetes)",
  "Serverless Security",
  "DevSecOps Principles",
  "Clean Desk Policy",
  "Information Governance",
  "E-commerce Security",
  "Web Application Firewalls (WAF)",
  "Denial-of-Service (DoS/DDoS) Attacks",
  "Man-in-the-Middle (MitM) Attacks",
  "Zero-Day Vulnerabilities",
  "Security Awareness Culture",
  "Penetration Testing Basics",
  "Code Review Best Practices",
  "Secure Configuration Management",
  "Log Management and Analysis",
  "Disaster Recovery and Business Continuity",
  "Social Media Security",
  "Cybersecurity Frameworks (NIST, ISO 27001)",
  "Data Loss Prevention (DLP)",
  "Endpoint Detection and Response (EDR)",
  "Supply Chain Security",
  "Digital Certificates and PKI",
  "Bluetooth Security",
  "Email Security and Spoofing",
  "Secure Coding for Web",
  "Secure Coding for Mobile",
  "File-less Malware",
  "Credential Stuffing",
  "Spear Phishing",
  "Whaling Attacks",
  "Vishing and Smishing",
  "Baiting and Quid Pro Quo",
  "Tailgating",
  "Dumpster Diving (Physical and Digital)",
  "GDPR for Marketing Teams",
  "GDPR for HR Teams",
  "GDPR for Developers",
  "Kenya Data Protection Act (DPA)",
  "Compliance with Kenya's ODPC",
  "Kenya's Computer Misuse and Cybercrimes Act (CMCA)",
  "Data Subject Rights in Kenya",
  "Incident Reporting in Kenya (KE-CIRT/CC)",
  "Cross-Border Data Transfers under Kenyan Law",
  "Understanding CVEs",
  "OWASP Top 10",
  "Threat Intelligence",
  "Intrusion Detection/Prevention Systems (IDS/IPS)",
  "Cyber Hygiene",
  "DNS Security",
  "Tor and the Dark Web",
  "Cryptojacking",
  "AI in Cybersecurity",
  "Machine Learning for Threat Detection",
  "Blockchain Security",
  "Smart Contract Security",
  "Operational Technology (OT) Security",
  "SCADA and ICS Security",
  "Cloud Access Security Broker (CASB)",
  "Zero Trust Architecture",
  "Deception Technology",
  "User and Entity Behavior Analytics (UEBA)",
  "Brand Protection",
  "Domain Squatting",
  "Account Takeover Prevention",
  "Security by Design",
  "Privacy by Design",
  "Security Metrics and KPIs",
  "Legal and Regulatory Compliance in Cybersecurity",
  "Ethical Hacking",
  "Digital Footprint Management",
  "Child Online Safety",
  "Remote Work Security",
  "NETWORKS AND WEB SECURITY",
  "ADVANCED DIGITAL FORENSICS",
  "DISTRIBUTED LEDGER TECHNOLOGIES",
  "INTERNET OF THINGS (IoT)",
  "CLOUD COMPUTING AND SECURITY",
  "SYSTEMS AND DATABASE SECURITY",
  "RESEARCH METHODS IN COMPUTER SCIENCE",
  "MALWARE ANALYSIS",
  "RISK AND INCIDENT RESPONSE MANAGEMENT",
  "INFORMATION SYSTEMS SECURITY AND AUDIT",
  "AI AND CYBERSECURITY",
  "SOCIAL FACTORS IN CYBERSECURITY",
  "PROJECT"
];
